# Generated by Django 3.1.1 on 2021-01-14 18:03

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('confirmpassword', models.CharField(max_length=120)),
                ('present_address', models.TextField(blank=True, max_length=120, null=True)),
                ('permanent_address', models.TextField(blank=True, max_length=120, null=True)),
                ('job', models.CharField(blank=True, max_length=120, null=True)),
                ('birthday', models.DateField()),
                ('school', models.TextField(blank=True, max_length=120, null=True)),
                ('college', models.TextField(blank=True, max_length=120, null=True)),
                ('profilepicture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('coverpicture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('profilepicture_url', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('uservideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='usersociallink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceebook', models.CharField(max_length=120)),
                ('instragram', models.CharField(max_length=120)),
                ('linkedin', models.CharField(max_length=120)),
                ('snapchat', models.CharField(max_length=120)),
                ('github', models.CharField(max_length=120)),
                ('youtube', models.CharField(max_length=120)),
                ('twitter', models.CharField(max_length=120)),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='user_timeline_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timenine_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('idtimelineowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='user_profile_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('idoprofilewner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='user_cover_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('idcoverowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='user_compressed_timeline_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_picture', models.ImageField(upload_to='user_image')),
                ('idofuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='timelinephotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('userpic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=10000)),
                ('caption', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sdate', models.DateField(auto_now=True)),
                ('stime', models.TimeField(auto_now=True)),
                ('timeline_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('cover_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('video', models.FileField(upload_to='st_videos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.status')),
            ],
        ),
        migrations.CreateModel(
            name='replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=1000)),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.comments')),
            ],
        ),
        migrations.CreateModel(
            name='profilephotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('userpic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Liker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stat', models.IntegerField(default=0)),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.status')),
            ],
        ),
        migrations.CreateModel(
            name='friendrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friensname', models.CharField(max_length=120)),
                ('friensusername', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('contact', models.TextField(max_length=11)),
                ('email', models.EmailField(max_length=120)),
                ('user', models.ManyToManyField(to='UserProfile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='coverphotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('cover_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('userpic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile'),
        ),
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.status'),
        ),
        migrations.CreateModel(
            name='chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatname', models.CharField(max_length=120)),
                ('userchat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='allmessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.chatroom')),
                ('usermessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
    ]
