# Generated by Django 3.0.1 on 2021-03-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='shared_caption',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
