# Generated by Django 3.0.1 on 2021-03-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_status_shared_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
