# Generated by Django 3.0.1 on 2021-03-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_profile_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_status',
            field=models.IntegerField(default=0),
        ),
    ]
