# Generated by Django 3.0.1 on 2021-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_auto_20210323_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_status',
            field=models.TextField(max_length=5),
        ),
    ]
